#	$NetBSD$
#

HOSTPROGNAME=   ${_TOOL_PREFIX}mkhybrid
HOST_SRCDIR=    external/gpl2/mkhybrid/bin
HOST_CPPFLAGS=  -I${.CURDIR}

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"
