#	$NetBSD$

.include <bsd.hostinit.mk>

HOSTPROGNAME=	${_TOOL_PREFIX}macppc_mkboothfs
HOST_SRCDIR=	sys/arch/macppc/stand/mkboothfs

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"
