#	$NetBSD: Makefile,v 1.1 2024/06/08 13:03:41 tsutsui Exp $

.include <bsd.hostinit.mk>

HOSTPROGNAME=	${_TOOL_PREFIX}macppc_installboot
HOST_SRCDIR=	sys/arch/macppc/stand/installboot

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"
