#	$NetBSD$

.include <bsd.hostinit.mk>

HOSTPROGNAME=	${_TOOL_PREFIX}macppc_installboot
HOST_SRCDIR=	distrib/cdrom/macppc_installboot

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"
